site_name: Intro to Git and Development
theme:
  name: material
  features:
    - navigation.top
    - navigation.tracking
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light Mode
      primary: blue
      accent: cyan
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        name: Dark Mode
        icon: material/weather-night
      primary: blue
      accent: cyan
  icon:
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - meta
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

repo_url: https://github.com/thehedgefrog/intro-to-git

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thehedgefrog/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/thehedgefrog

copyright: Copyright &copy; 2022 thehedgefrog

nav:
  - index.md
  - system-setup.md
  - setup-gpg.md